# Build stage
# Start with the dotnet:2.1-sdk image
FROM microsoft/dotnet:2.1-sdk AS build

# Set a working directory
WORKDIR /app

# Copy & restore project files
COPY src/Interface/Interface.csproj ./src/Interface/
RUN dotnet restore src/Interface/Interface.csproj
COPY src/Service/Service.csproj ./src/Service/
RUN dotnet restore src/Service/Service.csproj
COPY src/Client/Client.csproj ./src/Client/
RUN dotnet restore src/Client/Client.csproj
COPY src/Process/Process.csproj ./src/Process/
RUN dotnet restore src/Process/Process.csproj
COPY test/Service.Test/Service.Test.csproj ./test/Service.Test/
RUN dotnet restore test/Service.Test/Service.Test.csproj
COPY test/Client.Test/Client.Test.csproj ./test/Client.Test/
RUN dotnet restore test/Client.Test/Client.Test.csproj

# Copy src
COPY . .

# Test
##RUN dotnet test test/Service.Test/Service.Test.csproj \
##    && dotnet test test/Client.Test/Client.Test.csproj
